### ISSUE TITLE
Grid add row with column sort causes grid to repaint mid update

### ISSUE THREAD

**Issue by Fgarmon** [telerik/kendo-vue#10]
## I'm submitting a...

 
* Bug report 
 
 

## Current behavior

When adding a row to a grid that currently has a column sorted, once data is entered in the new record (sorted column) the grid is resorted mid edit.

## Expected behavior

Grid should not resort until the save button is pressed. Or not at all.
## Minimal reproduction of the problem with instructions

https://jcevsc.stackblitz.io/

in the above link, press the "Add New" button.
in the name field type "z", then press tab.

you will notice the grid resort.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 72

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by zdravkov** [comment]
It seems like a demo issue related with the concrete case - editing + sorting. In this case the computed property is playing a little trick because it is updated on every change of the collection. One possible solution is to update the data with a function one every place you want it to instead of using a computed property as it is done [here](https://stackblitz.com/edit/jcevsc-qniu5x?file=index.js).
