### ISSUE TITLE
Native Tooltip doesn't appear correctly when applied to Icon or SVG

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#239]
**Describe the bug**
Then using the Native Tooltip with Icon tag or SVG, the component is displayed aside from the hovered element. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/vue-tuelh4?file=src%2FApp.vue,src%2Fstyle.scss)
2. Hover either the Icon element or the SVG 

**Expected behavior**
The Tooltip should appear exactly below the hovered element. 

**Screenshots**
Icon:
![image](https://user-images.githubusercontent.com/41293735/168063077-295f059c-1f8c-4002-914c-e355b056a9fe.png)
SVG:
![image](https://user-images.githubusercontent.com/41293735/168063135-6ee09000-67d1-4be0-945e-ab7e969def0f.png)

**Comment by zdravkov** [comment]
By default the position of the tooltip is 'auto' and in this case it is positioning itself so that is is visible on the screen. Having this in  mind this positioning is expected with this setting. If we want to position the tooltip so that it is pointing the icon we can set the position to 'bottom' for example - :position="'bottom'" - https://stackblitz.com/edit/vue-faurrm?file=src%2FApp.vue
If we have an internal item and we don't want it to be different than its parent we ca add the pointer-events: none; to the child element as for example it is done in this example - https://stackblitz.com/edit/vue-xkmrkn?file=package.json,public%2Findex.html,src%2FApp.vue
