### ISSUE TITLE
Column menu filter variable number of filters

### ISSUE THREAD

**Issue by bmikaili** [telerik/kendo-vue#349]
I did not see it in the docs so I assume it is not possible unless u customize it:

I would like to be able to do n amount of AND or OR in the column menu filer of kendo grid. This is currently only possible using a custom filter.

**Comment by zdravkov** [comment]
Yes - currently such scenario is not available as an inbuilt functionality. 
If you want to have such behavior you will have you use custom menu as here - https://www.telerik.com/kendo-vue-ui/components/grid/filtering/filter-menu/#toc-customizing-the-filter-component
One other possible approach that you could take if you need such behavior is to check our [Filter component](https://www.telerik.com/kendo-vue-ui/components/datatools/filter/) that provides similar behavior yet it is not inside the column menu.
Meanwhile if you have further questions or you observe other issues please don't hesitate to let us know again. In such cases, we recommend creating an account and submitting a support ticket so that we could provide a better customer support - https://www.telerik.com/support/kendo-ui-for-vue.
