### ISSUE TITLE
Mouse events not working on a custom component in header cell of Kendo grid 

### ISSUE THREAD

**Issue by i-iktear** [telerik/kendo-vue#369]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/26440367/224562045-bdcbead5-1db0-4435-babe-43b86a5351db.png">

I have added an input box in the header. but it's not getting mouse click event properly.

**Comment by zdravkov** [comment]
Hi @i-iktear ,

I have tested a scenario with input in a header cell in Kendo UI for Vue Grid bug the click was thrown as expected. Here is my test example - https://stackblitz.com/edit/dyb7dq?file=src%2Fmain.vue
Please review it and let me know what else should I add or do in order to replicate the issue.

Greetings,
Plamen

**Comment by zdravkov** [comment]
Closing for now because it seems to be working correctly - if you have further questions please let us know or submit a support ticket in our [support system](https://www.telerik.com/support/kendo-ui-for-vue).
