### ISSUE TITLE
[Bug] [Grid] Warning appears in the console when using Grid with Nuxt

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#457]
**Describe the bug**
The following warning appears in the browser's console when using the Native Grid in Nuxt context:
<img width="1496" alt="image" src="https://github.com/telerik/kendo-vue/assets/41293735/90af6ac3-6152-4c44-9777-5e73ef575cdb">

**To Reproduce**
1. Open [this example](https://stackblitz.com/edit/nuxt-starter-vjdsru?file=components%2FSampleGrid.vue)
2. Check the browser's console

**Expected behavior**
No warnings or errors should appear in the console

**Comment by zdravkov** [comment]
We have inspected the issue deeper and it seems to be only happening in the stackblitz environment due to some specifics in our license warning check. Outside of the Stackblitz Nuxt environment once you [setup your license](https://www.telerik.com/kendo-vue-ui/components/my-license/) the warning is not observed. Having this in mind we are closing the issue as it is not relevant in a real world usage scenario.
