### ISSUE TITLE
[Bug][Drawer] DrawerItem content is ignored for the custom item 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#607]
**Describe the bug**
With version 5.2.0 the custom content of the DrawerItem used in a custom item is ignored

**To Reproduce**
https://stackblitz.com/edit/f9cq7g-ugdbxy?file=src%2Fmain.vue,package.json

Changing the layout package version to 5.1.0 shows the expected behavior

**Expected behavior**
The custom content of the DrawerItem should be rendered

**Comment by PekoPPT** [comment]
The bug is fixed and the fix is available in the latest dev version of the Kendo UI for Vue suite. 

[Here is a runnable example](https://stackblitz.com/edit/f9cq7g-6aqkie?file=src%2Fmain.vue,package.json) in which the expected behavior can be tested. The fix will be available with the next official version of the Kendo UI for Vue Native suite.
