### ISSUE TITLE
TypeError: cyclic object value  

### ISSUE THREAD

**Issue by majeeddl** [telerik/kendo-vue#86]
I see error when I want to run following code :

`
JSON.stringify( treeview.dataSource.data() )

`
error "TypeError: cyclic object value " is showing in debug console.

this issue is related to  ( "@progress/kendo-ui": "2020.3.1021" ) and error does not show when I downgrade it to 2020.3.915 .

**Comment by zdravkov** [comment]
Hi @majeeddl ,
I have tested the issue in the attached project but could not observe the issue. Please review it and let me know what else should be done or added in order to replicate it.
[vue2-typescript.zip](https://github.com/telerik/kendo-vue/files/5545052/vue2-typescript.zip)

Greetings,
Plamen

**Comment by zdravkov** [comment]
Closing this issue because of the insufficient information about it.
